### ISSUE TITLE
Can I use this on Pixel 3(blueline)?

### ISSUE THREAD

**Issue by Tsaitou7361** [edk2-porting/edk2-msm#370]
### Prerequisites

* [x] Have you read the wiki?
* [ ] Is your device in the supported list?
* [x] Does the device have a Snapdragon SOC which is supported in this repo?

### Description

If I chose a version which support Qualcomm Snapdragon 845, will it work fine on Google Pixel 3?

**Comment by coreycusick** [comment]
From my knowledge, no. Most devices have a very different partition table and therefore if it does boot at all ,expect massive issues. Not to mention screen resolution differences, and Windows could never boot due to the ACPI table being different. A few exceptions do occur from my testing, for example the OnePlus 7T image does work on a 7, same as the OP6 and 6T, with minor issues. Fair warning, the guide specifically says pixel devices do have an issue with wiping the entire flash chip bricking the phone, which is very very bad and as far as I know is considered unrepairable. I realize this issue was opened months ago, and hopefully this answers your question and you will close this issue
